# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Redlib installation tasks
  when: redlib_enabled | bool
  tags:
    - setup-all
    - setup-redlib
    - install-all
    - install-redlib
  block:
    - name: Validate Redlib configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Redlib
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Redlib uninstallation tasks
  when: not redlib_enabled | bool
  tags:
    - setup-all
    - setup-redlib
  block:
    - name: Uninstall Redlib
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
