# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Redlib settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - redlib_uid
    - redlib_gid
    - redlib_hostname
    - redlib_path_prefix
    - redlib_container_network

- name: Run if Traefik is enabled
  when: redlib_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Redlib are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - redlib_container_labels_traefik_hostname
        - redlib_container_labels_traefik_path_prefix

    - name: Fail if redlib_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          redlib_container_labels_traefik_path_prefix (`{{ redlib_container_labels_traefik_path_prefix }}`) must be `/`.
          Redlib does not support hosting under a subpath yet.
      when: "redlib_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `redlib_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if redlib_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          redlib_container_labels_traefik_path_prefix (`{{ redlib_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/redlib`).
      when: "redlib_container_labels_traefik_path_prefix != '/' and redlib_container_labels_traefik_path_prefix[-1] == '/'"
