# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "redlib_http_header_content_permission_policy", "new": "redlib_http_header_permissions_policy" }

- name: Fail if required Redlib settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - redlib_uid
    - redlib_gid
    - redlib_hostname
    - redlib_path_prefix
    - redlib_container_network

- name: Fail if Redlib default theme is invalid
  ansible.builtin.fail:
    msg: >-
      redlib_environment_variables_redlib_default_theme must be 'system', 'light', 'dark', 'black', 'dracula', 'nord', 'laserwave', 'violet', 'gold', 'rosebox', 'gruvboxdark', or 'gruvboxlight'
  when: "redlib_environment_variables_redlib_default_theme not in ['system', 'light', 'dark', 'black', 'dracula', 'nord', 'laserwave', 'violet', 'gold', 'rosebox', 'gruvboxdark', 'gruvboxlight']"

- name: Fail if Redlib default front page is invalid
  ansible.builtin.fail:
    msg: >-
      redlib_environment_variables_redlib_default_front_page must be 'default', 'popular', or 'all'
  when: "redlib_environment_variables_redlib_default_front_page not in ['default', 'popular', 'all']"

- name: Fail if Redlib default layout is invalid
  ansible.builtin.fail:
    msg: >-
      redlib_environment_variables_redlib_default_layout must be 'card', 'clean', or 'compact'
  when: "redlib_environment_variables_redlib_default_layout not in ['card', 'clean', 'compact']"

- name: Fail if Redlib default post sort method is invalid
  ansible.builtin.fail:
    msg: >-
      redlib_environment_variables_redlib_default_post_sort must be 'hot', 'new', 'top', 'rising', or 'controversial'
  when: "redlib_environment_variables_redlib_default_post_sort not in ['hot', 'new', 'top', 'rising', 'controversial']"

- name: Fail if Redlib default comment sort method is invalid
  ansible.builtin.fail:
    msg: >-
      redlib_environment_variables_redlib_default_comment_sort must be 'confidence', 'top', 'new', 'controversial', or 'old'
  when: "redlib_environment_variables_redlib_default_comment_sort not in ['confidence', 'top', 'new', 'controversial', 'old']"

- name: Run if Traefik is enabled
  when: redlib_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Redlib are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - redlib_container_labels_traefik_hostname
        - redlib_container_labels_traefik_path_prefix

    - name: Fail if redlib_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          redlib_container_labels_traefik_path_prefix (`{{ redlib_container_labels_traefik_path_prefix }}`) must be `/`.
          Redlib does not support hosting under a subpath yet.
      when: "redlib_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `redlib_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if redlib_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          redlib_container_labels_traefik_path_prefix (`{{ redlib_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/redlib`).
      when: "redlib_container_labels_traefik_path_prefix != '/' and redlib_container_labels_traefik_path_prefix[-1] == '/'"
